var tools={setHome:function(obj,hostname){if(!$.browser.msie){alert("您的浏览器不支持自动设置主页，请使用浏览器菜单手动设置。");return;}
var host=hostname;if(!host){host=window.location.href;}
obj.style.behavior='url(#default#homepage)';obj.setHomePage(host);},cookie:{set:function(name,value,expires,path,domain){if(typeof expires=="undefined"){expires=365;}
expires=new Date(new Date().getTime()+ 1000*3600*24*expires);document.cookie=name+"="+ escape(value)+((expires)?"; expires="+ expires.toGMTString():"")+((path)?"; path="+ path:"; path=/")+((domain)?";domain="+ domain:"");},get:function(name){var arr=document.cookie.match(new RegExp("(^| )"+ name+"=([^;]*)(;|$)"));if(arr!=null){return unescape(arr[2]);}
return null;},clear:function(name,path,domain){if(this.get(name)){document.cookie=name+"="+((path)?"; path="+ path:"; path=/")+((domain)?"; domain="+ domain:"")+";expires=Fri, 02-Jan-1970 00:00:00 GMT";}}},format:function(_,B){if(arguments.length>1){var F=tools.format,H=/([.*+?^=!:${}()|[\]\/\\])/g,C=(F.left_delimiter||"{").replace(H,"\\$1"),A=(F.right_delimiter||"}").replace(H,"\\$1"),E=F._r1||(F._r1=new RegExp("#"+ C+"([^"+ C+ A+"]+)"+ A,"g")),G=F._r2||(F._r2=new RegExp("#"+ C+"(\\d+)"+ A,"g"));if(typeof(B)=="object"){var result=_.replace(E,function(_,A){var $=B[A];if(typeof $=="function")$=$(A);return typeof($)=="undefined"?"":$});return result;}else if(typeof(B)!="undefined"){var D=Array.prototype.slice.call(arguments,1),$=D.length;return _.replace(G,function(A,_){_=parseInt(_,10);return(_>=$)?A:D[_]})}}
return _},pngfix:function(img){if(window.XMLHttpRequest){return}
var imgStyle="display:inline-block; "+ img.style.cssText;var strNewHTML="<span class=\""+ img.className+"\" title=\""+ img.title+"\" style=\"width:"+ img.clientWidth+"px; height:"+ img.clientHeight+"px;"+ imgStyle+";"+"filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='"+ img.src+"', sizingMethod='crop');\"></span>";img.outerHTML=strNewHTML;},dateFormat:function(format){var now=new Date((new Date).getTime()+ 864E5);var o={"M+":now.getMonth()+ 1,"d+":now.getDate(),"h+":now.getHours(),"m+":now.getMinutes(),"s+":now.getSeconds(),"q+":Math.floor((now.getMonth()+ 3)/ 3),
"S":now.getMilliseconds()}
if(/(y+)/.test(format)){format=format.replace(RegExp.$1,(now.getFullYear()+"").substr(4- RegExp.$1.length));}
for(var k in o){if(new RegExp("("+ k+")").test(format)){format=format.replace(RegExp.$1,RegExp.$1.length==1?o[k]:("00"+ o[k]).substr((""+ o[k]).length));}}
return format;}};var searchData={sougou:{action:"https://www.sogou.com/sogou",name:"query",btn:"搜狗搜索",img:["http://www.jspoo.com/sougou.png","搜狗搜索"],url:"https://www.sogou.com/",params:{ie:"utf-8"}},web:{action:"https://www.baidu.com/s",name:"wd",btn:"百度一下",img:["http://www.jspoo.com/baidu.png","百度首页"],url:"https://www.baidu.com/",params:{tn:"baidu",ie:"utf-8"}},so:{action:"https://www.so.com/s",name:"q",btn:"360搜索",img:["http://www.jspoo.com/360.png","360搜索"],url:"https://www.so.com/",params:{ie:"utf-8"}},neets:{action:"https://neets.cc/search ",name:"key",btn:"全网影视",img:["http://www.jspoo.com/neets.png","全网影视"],url:"https://neets.cc/",params:{}},bing:{action:"http://cn.bing.com/search",name:"q",btn:"必应搜索",img:["http://www.jspoo.com/bing.png","必应搜索"],url:"http://cn.bing.com/",params:{}},weibo:{action:"https://s.weibo.com/weibo",name:"q",btn:"微博搜索",img:["http://www.jspoo.com/weibo.png","微博搜索"],url:"https://weibo.com/",params:{}},taobao:{action:"https://s.taobao.com/search",name:"q",btn:"淘宝搜索",img:["http://www.jspoo.com/taobao.png","淘宝网"],url:"https://www.taobao.com/",params:{}},yunsou:{action:"https://www.ttyunsou.com/s",name:"keyword",btn:"云搜一下",img:["http://www.jspoo.com/ysou.png","云搜一下"],url:"https://www.ttyunsou.com",params:{o:"1",t:"0"}},google:{action:"https://www.google.com/",name:"q",btn:"谷歌搜索",img:["http://www.jspoo.com/google.png","谷歌搜索"],url:"https://www.google.com/",params:{}}}
$(function(){function adCut(bigNum){var num=0;function adShow(){var len=$('.atest-list').eq(bigNum).children('li').length;if(num>=len- 1){num=0;}else{num++;}
$('.atest-list').eq(bigNum).children('li').eq(num).slideDown().siblings('li').slideUp();}
setInterval(adShow,4000);}
var setSearchForm=function(type){var form=$('#j_search_form'),btn=$("#j_search_btn"),logo=$("#j_search_logo"),word=$("#search-text");form.find('input[type="hidden"]').remove();var data=searchData[type];form.attr('action',data.action);for(i in data.params){$('<input type="hidden" value="'+ data.params[i]+'" name="'+ i+'" />').appendTo(form);}
word.attr('name',data.name);logo.attr('href',data.url);logo.find('img').attr('src',data.img[0]).attr('alt',data.img[1]);btn.html(data.btn);word.focus();if(type=='web'){$('#j_auto_btn').css('visibility','visible');}else{$('#j_auto_btn').css('visibility','hidden');}
$("#auto_list").css("visibility","hidden");$('#j_key_'+ type).show().siblings().hide();}
setSearchForm("web")
$('#j_search_tab').find('li').click(function(){var rel=$(this).attr('rel');var thisIndex=$(this).index();$(this).addClass('current').siblings().removeClass('current');setSearchForm(rel);});var isSearchInAutoList=false
$("#j_auto_btn").click(function(e){e.stopPropagation();e.preventDefault();$(this).find(".num").css('visibility','hidden');var isHidden=($("#auto_list").css("visibility")=="hidden");if(isHidden){$("#auto_list").css("visibility","visible");}else{$("#auto_list").css("visibility","hidden");}
$("#auto_suggest").css("visibility","hidden");});$("#auto_list").delegate('li','mouseover',function(){$(this).addClass('autocomplete-hover').siblings().removeClass('autocomplete-hover');isSearchInAutoList=true;}).delegate('li','mouseout',function(){isSearchInAutoList=false;})
$(document).click(function(){if(!isSearchInAutoList){$("#auto_list").css("visibility","hidden");}
$("#auto_suggest").css("visibility","hidden");});for(var i=0,len=$('#all_atest ul').length;i<len;i++){adCut(i);}
window.searchSug=function(data){$("#auto_list").css("visibility","hidden");if(data.s&&data.s.length>0){var $list=$("#auto_suggest ul");$list.html("");for(var i=0;i<data.s.length&&i<5;i++){var key=data.s[i];var num=i+ 1;$list.append('<li><i class="auto-raq auto-'+ num+'">'+ num+'</i><i class="auto-key"><a href="#" target="_blank" title="'+ key+'">'+ key+'</a></i></li>');}
$("#auto_suggest").css("visibility","visible");}}
$("#auto_suggest").delegate('a','click',function(){var keyword=$(this).text();$("#search-text").val(keyword);$("#j_search_btn").trigger("click");return false;});var doSearchTimer=null;$("#search-text").keyup(function(evt){if(evt.keyCode==38||evt.keyCode==40){if($("#auto_suggest").css("visibility")!="visible"){return}
var $list=$("#auto_suggest li");var n=-1;$list.each(function(i){if($(this).hasClass("autocomplete-hover")){n=i;return false;}});if(evt.keyCode==38){if(n<0){n=0;}
n=n- 1;if(n<0){n=n+ $list.length}}else{n=(n+ 1)%$list.length;}
$list.removeClass("autocomplete-hover");var text=$list.eq(n).addClass("autocomplete-hover").find(".auto-key").text();$("#search-text").val(text);return;}
var keyword=$(this).val();if(!keyword){return;}
if(doSearchTimer){clearTimeout(doSearchTimer);doSearchTimer=null;}
doSearchTimer=setTimeout(function(){var data={wd:keyword,cb:"searchSug",};$.ajax({type:"get",async:false,url:"http://suggestion.baidu.com/su",data:data,dataType:"jsonp",jsonp:"callback",jsonpCallback:"searchSug",error:function(){}});},100);});})
$(function(){var box=$('.speedy');var btn=$('.close-speedy');var oSpeedyChange;btn.click(function(){box.toggleClass('speedy-add');if(box.hasClass('speedy-add')){tools.cookie.set('_speedy',1);}else{tools.cookie.set('_speedy',0);}});if(tools.cookie.get('_speedy')==undefined){oSpeedyChange=tools.cookie.set('_speedy',1);}else{oSpeedyChange=tools.cookie.get('_speedy');}
if(oSpeedyChange==1){box.addClass('speedy-add');}else{box.removeClass('speedy-add');}
var ul=$('.speedy-list');var li=ul.children('li');var _this;li.hover(function(){_this=$(this);_this.siblings('li').find('.sl-show').hide();_this.find('.sl-show').show();var rel=_this.find('.photos').children('img').attr('rel');_this.find('.photos').children('img').attr('src',rel);},function(){$(this).find('.sl-show').hide();});var closeBtn=$('.sl-close-btn');closeBtn.click(function(){$(this).parents('.sl-show').hide();});function smallWidth(){var windowWidth=$(window).width();if(windowWidth<1100){box.hide();}else{box.show();}}
smallWidth();$(window).resize(function(){smallWidth();});})
$(function(){var ul=$('.function-list');ul.children('li').hover(function(){$(this).addClass('current').siblings('li').removeClass('current');},function(){$(this).removeClass('current');});function goTop(){if($(window).scrollTop()>500){$('.down-up').children('a').attr('class','go-top');}else{$('.down-up').children('a').attr('class','go-bottom');}}
goTop();$(window).scroll(function(){goTop();});$('.function-list .go-top').live('click',function(){$('html,body').animate({scrollTop:0},400);});$('.function-list .go-bottom').live('click',function(){$('html,body').animate({scrollTop:$(document).height()+'px'},400);});})
$(function(){$(document).mousedown(function(e){var mf=$('#mail-f'),m=$('#mail')[0];if(mf.css('display')=='none')return;if(!($.contains(mf[0],e.target)||m==e.target||$.contains(m,e.target))){mf.hide();}});$('#mail').click(function(){if($('#mail-f').css('display')!='none'){$('#mail-f').hide();return false;}
$('#mail-f').show();return false;});$('#mail-f .content a').click(function(){window.open(this.href);$('#mail-f').hide();return false;});$('#mail-close').click(function(){$('#mail-f').hide();return false;});})
$(function(){$(document).mousedown(function(e){var mf=$('#yp-f'),m=$('#yp')[0];if(mf.css('display')=='none')return;if(!($.contains(mf[0],e.target)||m==e.target||$.contains(m,e.target))){mf.hide();}});$('#yp').click(function(){if($('#yp-f').css('display')!='none'){$('#yp-f').hide();return false;}
$('#yp-f').show();return false;});$('#yp-f .content a').click(function(){window.open(this.href);$('#yp-f').hide();return false;});$('#yp-close').click(function(){$('#yp-f').hide();return false;});})
$(function(){$(document).mousedown(function(e){var mf=$('#wx-f'),m=$('#wx')[0];if(mf.css('display')=='none')return;if(!($.contains(mf[0],e.target)||m==e.target||$.contains(m,e.target))){mf.hide();}});$('#wx').click(function(){if($('#wx-f').css('display')!='none'){$('#wx-f').hide();return false;}
$('#wx-f').show();return false;});$('#wx-f .content a').click(function(){window.open(this.href);$('#wx-f').hide();return false;});$('#wx-close').click(function(){$('#wx-f').hide();return false;});})